apiVersion: v1
kind: ConfigMap
metadata:
  name: storyforge-config
  namespace: storyforge
data:
  APP_NAME: "storyforge-api"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  KAFKA_BOOTSTRAP_SERVERS: "storyforge-kafka.storyforge.svc.cluster.local:9092"
  REDIS_HOST: "storyforge-redis.storyforge.svc.cluster.local"
  REDIS_PORT: "6379"
